// Regenerates src/tracker/tracker-html.ts from src/tracker/tracker.html (the
// owner's "Quiet Progress" Task Tracker, kept 1:1). Run after replacing
// tracker.html:  node scripts/gen-tracker.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const html = readFileSync(new URL('../src/tracker/tracker.html', import.meta.url), 'utf8');
writeFileSync(
  new URL('../src/tracker/tracker-html.ts', import.meta.url),
  `// GENERATED by scripts/gen-tracker.mjs from tracker.html — do not edit.\nexport const TRACKER_HTML = ${JSON.stringify(html)};\n`,
);
console.log('tracker-html.ts', html.length, 'chars');
