// Regenerates src/core/core-html.ts from src/core/core.html (the owner's
// Claude-designed "Persons Staff Core v2" page, kept 1:1). Run after
// replacing core.html:  node scripts/gen-core.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const html = readFileSync(new URL('../src/core/core.html', import.meta.url), 'utf8');
writeFileSync(
  new URL('../src/core/core-html.ts', import.meta.url),
  `// GENERATED by scripts/gen-core.mjs from core.html — do not edit.\nexport const CORE_HTML = ${JSON.stringify(html)};\n`,
);
console.log('core-html.ts', html.length, 'chars');
